name: Build and Deploy APK
on:
  workflow_run:
    workflows: ["CI Android Workflow"]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Android APK
        run: ./gradlew assembleDebug

      - name: Rename APK with Timestamp
        run: mv app/build/outputs/apk/debug/app-debug.apk "testBuilds/demo-$(date +'%Y%m%d%H%M%S').apk"

      - name: Add APK to Repository Folder
        run: mv "testBuilds/demo-*.apk" testBuilds/
        
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add testBuilds/*
          git commit -m "Add debug APK"
          git push
